import { createRequire } from 'node:module';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const requirePackage = createRequire(import.meta.url);
const { chromium } = requirePackage(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${process.env.TEST_BASE_URL || 'http://localhost:3001'}/editor?source=photo`);
  await page.locator('input[type=file]').first().setInputFiles('test-results/portrait.jpg');
  await page.getByText('자동 맞춤 완료', { exact: true }).waitFor({ timeout: 90000 });
  await page.locator('canvas').first().waitFor();
  await page.screenshot({ path: 'test-results/natural-desktop.png', fullPage: true });
  const before = await page.locator('canvas').first().evaluate(c => c.toDataURL());
  fs.writeFileSync('test-results/applied.png', Buffer.from(before.split(',')[1], 'base64'));
  const slider = page.locator('label').filter({ hasText: '진하기' }).locator('input[type=range]').first();
  await slider.fill('0');
  await page.waitForTimeout(150);
  const zero = await page.locator('canvas').first().evaluate(c => c.toDataURL());
  fs.writeFileSync('test-results/original.png', Buffer.from(zero.split(',')[1], 'base64'));
  assert.notEqual(before, zero, 'intensity must affect rendered pixels');
  await slider.fill('1');
  await page.waitForTimeout(150);
  await page.screenshot({ path: 'test-results/natural-intensity.png', fullPage: true });
  const full = await page.locator('canvas').first().evaluate(c => c.toDataURL());
  const arch = page.locator('label').filter({ hasText: /^아치/ }).locator('input[type=range]').first();
  await arch.fill('1');
  await page.waitForTimeout(150);
  assert.notEqual(await page.locator('canvas').first().evaluate(c => c.toDataURL()), full, 'arch must affect pixels');
  await arch.fill('0');
  await page.getByRole('button', { name: /남성 헤어스트로크/ }).click();
  const width = page.locator('label').filter({ hasText: '털 한 올 굵기' }).locator('input[type=range]').first();
  await width.fill('0.5');
  await page.waitForTimeout(700);
  await page.getByRole('button', { name: /원본 변형 \+ 털결 보충/ }).click();
  await page.waitForTimeout(300);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '결과 저장', exact: true }).click();
  const download = await downloadPromise;
  await download.saveAs('test-results/export.png');
  assert.ok(fs.statSync('test-results/export.png').size > 10000);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/natural-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  fs.writeFileSync('test-results/browser-smoke.json', JSON.stringify({ passed: true, errors }, null, 2));
  console.log('PASS: face upload, detection, intensity pixels, desktop/mobile, no page errors');
} finally {
  await browser.close();
}
