import { createRequire } from 'node:module';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const requirePackage = createRequire(import.meta.url);
const { chromium } = requirePackage(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  await page.addInitScript(() => {
    const raf = window.requestAnimationFrame.bind(window);
    window.__renderTimes = [];
    window.requestAnimationFrame = callback => raf(time => {
      const start = performance.now();
      callback(time);
      if (window.__measureDrag) window.__renderTimes.push(performance.now() - start);
    });
  });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${process.env.TEST_BASE_URL || 'http://localhost:3001'}/editor?source=photo`);
  await page.locator('input[type=file]').first().setInputFiles(process.env.TEST_FACE || 'test-results/portrait.jpg');
  await page.getByText('자동 맞춤 완료', { exact: true }).waitFor({ timeout: 90000 });
  await page.locator('canvas').first().waitFor();
  await page.screenshot({ path: 'test-results/natural-desktop.png', fullPage: true });
  const before = await page.locator('canvas').first().evaluate(c => c.toDataURL());
  fs.writeFileSync('test-results/applied.png', Buffer.from(before.split(',')[1], 'base64'));
  const slider = page.locator('label').filter({ hasText: '진하기' }).locator('input[type=range]').first();
  await slider.fill('0');
  await page.waitForTimeout(150);
  const zero = await page.locator('canvas').first().evaluate(c => c.toDataURL());
  fs.writeFileSync('test-results/original.png', Buffer.from(zero.split(',')[1], 'base64'));
  assert.notEqual(before, zero, 'intensity must affect rendered pixels');
  await slider.fill('1');
  await page.waitForTimeout(150);
  await page.screenshot({ path: 'test-results/natural-intensity.png', fullPage: true });
  const full = await page.locator('canvas').first().evaluate(c => c.toDataURL());
  const arch = page.locator('label').filter({ hasText: /^아치/ }).locator('input[type=range]').first();
  await arch.fill('1');
  await page.waitForTimeout(150);
  assert.notEqual(await page.locator('canvas').first().evaluate(c => c.toDataURL()), full, 'arch must affect pixels');
  await arch.fill('0');
  await page.getByRole('button', { name: /가상 눈썹 만들기/ }).click();
  assert.equal(await page.getByRole('button', { name: /완성형 시뮬레이션|자동 모드|강하게 정리/ }).count(), 0);
  await page.getByRole('button', { name: /^내추럴/ }).click();
  await page.waitForTimeout(700);
  const naturalVirtual = await page.locator('canvas').first().evaluate(c => c.toDataURL());
  const clarity = page.locator('label').filter({ hasText: /^선명도/ }).locator('input[type=range]').first();
  await clarity.fill('0');
  await page.waitForTimeout(250);
  const soft = await page.locator('canvas').first().evaluate(c=>c.toDataURL());
  await clarity.fill('1');
  await page.waitForTimeout(250);
  const sharp = await page.locator('canvas').first().evaluate(c=>c.toDataURL());
  assert.notEqual(soft,sharp,'clarity endpoints must change rendered hair pixels');
  fs.writeFileSync('test-results/clarity-soft.png',Buffer.from(soft.split(',')[1],'base64'));
  fs.writeFileSync('test-results/clarity-sharp.png',Buffer.from(sharp.split(',')[1],'base64'));
  await clarity.fill('0.88');
  await page.waitForTimeout(250);
  await page.getByRole('button', { name: /^아치형/ }).click();
  await page.waitForTimeout(300);
  assert.notEqual(await page.locator('canvas').first().evaluate(c => c.toDataURL()), naturalVirtual, 'virtual shape must change');
  await page.getByRole('button', { name: /^내추럴/ }).click();
  await page.waitForTimeout(300);
  assert.equal(await page.locator('canvas').first().evaluate(c => c.toDataURL()), naturalVirtual, 'shape changes must not accumulate');
  const bodyThickness = page.locator('label').filter({ hasText: /^두께/ }).locator('input[type=range]').first();
  const hairWidth = page.locator('label').filter({ hasText: '털 한 올 굵기' }).locator('input[type=range]').first();
  await bodyThickness.fill('1');
  await hairWidth.fill('1');
  await page.waitForTimeout(400);
  const thick = await page.locator('canvas').first().evaluate(c => c.toDataURL());
  assert.notEqual(thick, naturalVirtual, 'maximum body and strand width must change virtual eyebrows');
  await page.screenshot({ path: 'test-results/virtual-max-thickness.png', fullPage: true });
  await bodyThickness.fill('0');
  await hairWidth.fill('0');
  const canvas = page.getByLabel('눈썹 적용 미리보기');
  const rect = await canvas.boundingBox();
  const boxPixels = () => canvas.evaluate(c => {
    const p = c.getContext('2d').getImageData(0,0,c.width,c.height).data;
    const points = [];
    for(let i=0;i<p.length;i+=4) if(p[i]>248 && p[i+1]>208 && p[i+1]<221 && p[i+2]>124 && p[i+2]<141) points.push({x:(i/4)%c.width,y:Math.floor(i/4/c.width)});
    return {count:points.length,width:c.width,height:c.height,minX:Math.min(...points.map(p=>p.x)),maxX:Math.max(...points.map(p=>p.x)),minY:Math.min(...points.map(p=>p.y)),maxY:Math.max(...points.map(p=>p.y))};
  });
  assert.ok((await boxPixels()).count < 30, 'selection must stay hidden until an eyebrow is clicked');
  await page.mouse.click(rect.x+rect.width*0.35,rect.y+rect.height*0.4);
  await page.waitForTimeout(200);
  const selected = await boxPixels();
  assert.ok(selected.count>30,'virtual brow click must reveal handles');
  const beforeMove = await canvas.evaluate(c=>c.toDataURL());
  await page.evaluate(() => { window.__measureDrag = true; window.__renderTimes = []; });
  await page.mouse.move(rect.x+rect.width*0.35,rect.y+rect.height*0.4);
  await page.mouse.down();
  await page.mouse.move(rect.x+rect.width*0.38,rect.y+rect.height*0.42,{steps:5});
  await page.mouse.up();
  await page.waitForTimeout(200);
  assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),beforeMove,'drag must change virtual brow');
  const timing = await page.evaluate(() => { window.__measureDrag = false; return window.__renderTimes.filter(n=>n>1); });
  console.log('Drag frame callback times (ms):', timing.map(n=>Math.round(n)));
  fs.writeFileSync(`test-results/drag-${process.env.TEST_TIMING_LABEL || 'latest'}.json`, JSON.stringify(timing));
  const frame = await boxPixels();
  const corner = {x:rect.x+frame.maxX/frame.width*rect.width-2,y:rect.y+frame.maxY/frame.height*rect.height-2};
  await page.mouse.move(corner.x,corner.y);
  await page.mouse.down();
  await page.mouse.move(corner.x+25,corner.y+15,{steps:5});
  await page.mouse.up();
  await page.waitForTimeout(250);
  const resized = await boxPixels();
  assert.ok(resized.maxX-resized.minX>frame.maxX-frame.minX,'corner drag must enlarge frame');
  const rotation = {x:rect.x+(resized.minX+resized.maxX)/2/resized.width*rect.width,y:rect.y+(resized.minY+4)/resized.height*rect.height};
  const beforeRotation = await canvas.evaluate(c=>c.toDataURL());
  await page.mouse.move(rotation.x,rotation.y);
  await page.mouse.down();
  await page.mouse.move(rotation.x+15,rotation.y,{steps:5});
  await page.mouse.up();
  await page.waitForTimeout(250);
  assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),beforeRotation,'top handle must rotate eyebrow');
  const currentFrame = await boxPixels();
  const hit = {x:rect.x+(currentFrame.minX+currentFrame.maxX)/2/currentFrame.width*rect.width,y:rect.y+(currentFrame.minY+currentFrame.maxY)/2/currentFrame.height*rect.height};
  const beforeCopy = await canvas.evaluate(c=>c.toDataURL());
  await page.mouse.click(hit.x,hit.y,{button:'right'});
  await page.getByRole('menuitem',{name:'반대쪽 똑같이 하기'}).click();
  await page.waitForTimeout(250);
  assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),beforeCopy,'copy must modify opposite eyebrow');
  const cdp = await page.context().newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:hit.x,y:hit.y}]});
  await page.getByRole('menuitem',{name:'반대쪽 똑같이 하기'}).waitFor();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.getByRole('menuitem',{name:'반대쪽 똑같이 하기'}).click();
  await page.waitForTimeout(250);
  const withoutGuides = await canvas.evaluate(c=>c.toDataURL());
  await page.getByRole('button',{name:'가이드라인 생성',exact:true}).click();
  await page.waitForTimeout(250);
  assert.notEqual(await canvas.evaluate(c=>c.toDataURL()), withoutGuides, 'mapping must survive photo cropping and render visible lines');
  await page.screenshot({path:'test-results/mapping-and-copy.png',fullPage:true});
  await page.getByRole('button',{name:'가이드라인 해지',exact:true}).click();
  await page.mouse.click(rect.x+rect.width*0.5,rect.y+rect.height*0.85);
  await page.waitForTimeout(200);
  assert.ok((await boxPixels()).count<selected.count,'click outside must hide selection');
  await arch.fill('0.6');
  await bodyThickness.fill('0.4');
  await slider.fill('0.3');
  await page.getByRole('button',{name:'조정 초기화',exact:true}).click();
  await page.waitForTimeout(250);
  assert.equal(await arch.inputValue(),'0');
  assert.equal(await bodyThickness.inputValue(),'0');
  assert.equal(await slider.inputValue(),'0.86');
  assert.equal(await clarity.inputValue(),'0.88');
  assert.equal(await page.getByRole('button',{name:/^내추럴/}).getAttribute('aria-pressed'),'true');
  assert.ok((await boxPixels()).count<30,'reset must hide selection');
  const resetPixels=await canvas.evaluate(c=>c.toDataURL());
  await page.getByRole('button',{name:'조정 초기화',exact:true}).click();
  await page.waitForTimeout(250);
  assert.equal(await canvas.evaluate(c=>c.toDataURL()),resetPixels,'repeated reset must be stable');
  await page.getByRole('button', { name: /남성 일자형/ }).click();
  const width = page.locator('label').filter({ hasText: '털 한 올 굵기' }).locator('input[type=range]').first();
  await width.fill('0.5');
  await page.waitForTimeout(700);
  await page.getByRole('button', { name: /내 눈썹 다듬기/ }).click();
  await page.waitForTimeout(300);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '결과 저장', exact: true }).click();
  const download = await downloadPromise;
  await download.saveAs('test-results/export.png');
  assert.ok(fs.statSync('test-results/export.png').size > 10000);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button',{name:'조정 패널 열기'}).click();
  await arch.fill('0.4');
  await page.getByRole('button',{name:'조정 초기화',exact:true}).click();
  assert.equal(await arch.inputValue(),'0');
  await page.getByRole('button',{name:'사진 크게 보기'}).click();
  await page.waitForTimeout(350);
  await page.screenshot({ path: 'test-results/natural-mobile.png', fullPage: false });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  fs.writeFileSync('test-results/browser-smoke.json', JSON.stringify({ passed: true, errors }, null, 2));
  console.log('PASS: face upload, detection, intensity pixels, desktop/mobile, no page errors');
} finally {
  await browser.close();
}
